### PR TITLE
Wait until build has finished before deployment

### PR DESCRIPTION
**Pull request by jannikluhn**
[there might be a lot more small fixes coming, I don't know of a better way to test than merging to master...]

### CODE REVIEW

**Comment by ghost** [comment]
I don't understand what you're trying to solve and why I am assigned.

**Comment by jannikluhn** [comment]
Sorry, forgot to give an explanation. Wrote it down here: #12

**Comment by jannikluhn** [comment]
I've tested the full release process using my own account and it seems to work.

There are two errors during the compute image tree summaries step, but I don't think it matters because the command itself succeeds:

```
sha256sum: /usr/local/lib/node_modules/npm/node_modules/ajv/lib/.js: No such file or directory
Use of uninitialized value $digest in concatenation (.) or string at - line 46.
```

**Comment by ghost** [comment]
so, should we merge this PR?

**Comment by jannikluhn** [comment]
From my side, yes. But it hasn't been formally reviewed yet.

**Comment by ghost** [comment]
This is such a waste of time and money.

**Pull request merged**
